export const DASHBOARD_GREETING_PHRASES = [
  'Ready to learn',
  'Let us make progress',
  'Your study desk is ready',
  'Small steps, strong recall',
  'Time to sharpen concepts',
  'Back to the grind',
  'Let us build momentum',
  'One focused session at a time',
  'Fresh questions are waiting',
  'Your future doctor mode is on',
  'A little revision goes far',
  'Keep the streak alive',
  'Let us train your instincts',
  'Today is a good day to improve',
  'Your prep engine is warm',
  'Focus mode, activated',
  'Let us turn effort into marks',
  'Strong basics win exams',
  'Your next correct answer starts here',
  'Steady practice, better scores',
  'Let us clear another topic',
  'Your revision lane is open',
  'Clinical thinking starts now',
  'Make this session count',
  'Progress is waiting',
  'Let us beat yesterday',
  'Confidence grows question by question',
  'A focused mind learns faster',
  'Your exam prep continues',
  'Let us get one percent better',
] as const;

export const DASHBOARD_REVIEW_STORAGE_KEY = 'medmacs_dashboard_review_completed';
export const DASHBOARD_APP_VERSION = '7.1.0';
