// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.13.2'
        classpath 'com.google.gms:google-services:4.4.2'
    }
}

apply from: "variables.gradle"

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

subprojects {
    afterEvaluate { project ->
        if (project.hasProperty('android')) {
            project.android {
                if (namespace == null) {
                    namespace = "com.capacitor.plugins." + project.name.replaceAll(":", "")
                }
                buildTypes {
                    debug {
                        matchingFallbacks = ['release']
                    }
                }
            }
        }
    }
}

task clean(type: Delete) {
    delete rootProject.layout.buildDirectory
}
