ALTER TABLE public.profiles
ADD COLUMN IF NOT EXISTS flashcard_generated integer NOT NULL DEFAULT 0;

UPDATE public.profiles
SET flashcard_generated = GREATEST(
  flashcard_generated,
  CASE
    WHEN badges->'stats'->>'flashcardsGeneratedCount' ~ '^[0-9]+$'
      THEN (badges->'stats'->>'flashcardsGeneratedCount')::integer
    ELSE 0
  END
)
WHERE badges ? 'stats';

COMMENT ON COLUMN public.profiles.flashcard_generated IS 'Lifetime count of AI flashcards generated by the user.';
